// <auto-generated />
using System;
using AZ.Integrator.Stocks.Infrastructure.Persistence.EF.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AZ.Integrator.Stocks.Infrastructure.Persistence.EF.Domain.Migrations
{
    [DbContext(typeof(StockDbContext))]
    partial class StockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AZ.Integrator.Stocks.Domain.Aggregates.Stock.Stock", b =>
                {
                    b.Property<string>("PackageCode")
                        .HasColumnType("text")
                        .HasColumnName("package_code");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer")
                        .HasColumnName("threshold");

                    b.Property<uint?>("_groupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.HasKey("PackageCode");

                    b.ToTable("stocks", (string)null);
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Domain.Aggregates.Stock.StockLog", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<uint>("Id"));

                    b.Property<int>("ChangeQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("change_quantity");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("_packageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_code");

                    b.HasKey("Id");

                    b.HasIndex("_packageCode");

                    b.ToTable("stock_logs", (string)null);
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Domain.Aggregates.StockGroup.StockGroup", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<uint>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("stock_groups", (string)null);
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Domain.Aggregates.Stock.StockLog", b =>
                {
                    b.HasOne("AZ.Integrator.Stocks.Domain.Aggregates.Stock.Stock", null)
                        .WithMany("StockLogs")
                        .HasForeignKey("_packageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AZ.Integrator.Stocks.Domain.Aggregates.Shared.ValueObjects.OperatorCreationInformation", "CreationInformation", b1 =>
                        {
                            b1.Property<uint>("StockLogId")
                                .HasColumnType("bigint");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("OperatorId")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by_id");

                            b1.Property<string>("OperatorLogin")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by");

                            b1.HasKey("StockLogId");

                            b1.ToTable("stock_logs");

                            b1.WithOwner()
                                .HasForeignKey("StockLogId");
                        });

                    b.Navigation("CreationInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Domain.Aggregates.StockGroup.StockGroup", b =>
                {
                    b.OwnsOne("AZ.Integrator.Domain.SharedKernel.ValueObjects.ModificationInformation", "ModificationInformation", b1 =>
                        {
                            b1.Property<uint>("StockGroupId")
                                .HasColumnType("bigint");

                            b1.Property<DateTimeOffset>("ModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("modified_at");

                            b1.Property<Guid>("ModifiedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("modified_by");

                            b1.HasKey("StockGroupId");

                            b1.ToTable("stock_groups");

                            b1.WithOwner()
                                .HasForeignKey("StockGroupId");
                        });

                    b.OwnsOne("AZ.Integrator.Stocks.Domain.Aggregates.Shared.ValueObjects.OperatorCreationInformation", "CreationInformation", b1 =>
                        {
                            b1.Property<uint>("StockGroupId")
                                .HasColumnType("bigint");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("OperatorId")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by_id");

                            b1.Property<string>("OperatorLogin")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by");

                            b1.HasKey("StockGroupId");

                            b1.ToTable("stock_groups");

                            b1.WithOwner()
                                .HasForeignKey("StockGroupId");
                        });

                    b.Navigation("CreationInformation")
                        .IsRequired();

                    b.Navigation("ModificationInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Domain.Aggregates.Stock.Stock", b =>
                {
                    b.Navigation("StockLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
