version: '3.4'

services:
    az.integrator.db:
        image: "postgres:15"
        container_name: az-integrator-db
        ports:
          - "5432:5432"
        restart: always
        environment:
          - POSTGRES_PASSWORD=xr?8751A>H?S
        volumes:
          - postgres_data:/var/lib/postgresql/data
        networks:
          - az
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready" ]
          interval: 10s
          timeout: 5s
          retries: 5
      
volumes:
  postgres_data:
    driver: local

networks:
  az:
    driver: bridge
