services:
    az.integrator.db:
        image: "postgres:15"
        container_name: az-integrator-db
        ports:
          - "5432:5432"
        restart: always
        env_file:
          - env/postgres.env
        volumes:
          - postgres_data:/var/lib/postgresql/data
        networks:
          - az
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready" ]
          interval: 10s
          timeout: 5s
          retries: 5
    
    az.integrator.keycloak:
      image: quay.io/keycloak/keycloak:21.0.1
      ports:
        - "9080:8443"
      container_name: az-integrator-keycloak
      env_file:
        - env/keycloak.env
      command: --https-port=8443
      networks:
        - az
      volumes:
        - ./https/:/opt/keycloak/conf
      depends_on:
        az.integrator.db:
          condition: service_healthy
      
volumes:
  postgres_data:
    driver: local

networks:
  az:
    driver: bridge
