// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AZ.Integrator.Shared.Infrastructure.Persistence.EF.DbContexts.Domain.ParcelTemplate.Migrations
{
    [DbContext(typeof(TagParcelTemplates.Infrastructure.Persistence.EF.Domain.TagParcelTemplateDbContext))]
    [Migration("20231219073834_InitTagParcelTemplates")]
    partial class InitTagParcelTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AZ.Integrator.TagParcelTemplates.Domain.Aggregates.TagParcelTemplate.TagParcel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<uint>("Id"));

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.Property<string>("_tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.HasKey("Id");

                    b.HasIndex("_tag");

                    b.ToTable("tag_parcels", (string)null);
                });

            modelBuilder.Entity("AZ.Integrator.TagParcelTemplates.Domain.Aggregates.TagParcelTemplate.TagParcelTemplate", b =>
                {
                    b.Property<string>("Tag")
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.HasKey("Tag");

                    b.ToTable("tag_parcel_templates", (string)null);
                });

            modelBuilder.Entity("AZ.Integrator.TagParcelTemplates.Domain.Aggregates.TagParcelTemplate.TagParcel", b =>
                {
                    b.HasOne("AZ.Integrator.TagParcelTemplates.Domain.Aggregates.TagParcelTemplate.TagParcelTemplate", null)
                        .WithMany("Parcels")
                        .HasForeignKey("_tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AZ.Integrator.TagParcelTemplates.Domain.Aggregates.TagParcelTemplate.ValueObjects.Dimension", "Dimension", b1 =>
                        {
                            b1.Property<uint>("TagParcelId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Height")
                                .HasColumnType("double precision")
                                .HasColumnName("height");

                            b1.Property<double>("Length")
                                .HasColumnType("double precision")
                                .HasColumnName("length");

                            b1.Property<double>("Width")
                                .HasColumnType("double precision")
                                .HasColumnName("width");

                            b1.HasKey("TagParcelId");

                            b1.ToTable("tag_parcels");

                            b1.WithOwner()
                                .HasForeignKey("TagParcelId");
                        });

                    b.Navigation("Dimension");
                });

            modelBuilder.Entity("AZ.Integrator.TagParcelTemplates.Domain.Aggregates.TagParcelTemplate.TagParcelTemplate", b =>
                {
                    b.OwnsOne("AZ.Integrator.Domain.SharedKernel.ValueObjects.CreationInformationWithTenant", "CreationInformation", b1 =>
                        {
                            b1.Property<string>("TagParcelTemplateTag")
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by");

                            b1.Property<string>("TenantId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("tenant_id");

                            b1.HasKey("TagParcelTemplateTag");

                            b1.ToTable("tag_parcel_templates");

                            b1.WithOwner()
                                .HasForeignKey("TagParcelTemplateTag");
                        });

                    b.Navigation("CreationInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("AZ.Integrator.TagParcelTemplates.Domain.Aggregates.TagParcelTemplate.TagParcelTemplate", b =>
                {
                    b.Navigation("Parcels");
                });
#pragma warning restore 612, 618
        }
    }
}
