// <auto-generated />
using System;
using AZ.Integrator.Shared.Infrastructure.Persistence.EF.DbContexts.Domain.Stock;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AZ.Integrator.Shared.Infrastructure.Persistence.EF.DbContexts.Domain.Stock.Migrations
{
    [DbContext(typeof(StockDbContext))]
    partial class StockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AZ.Integrator.Stocks.Domain.Aggregates.Stock", b =>
                {
                    b.Property<string>("PackageCode")
                        .HasColumnType("text")
                        .HasColumnName("package_code");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("PackageCode");

                    b.ToTable("stocks", (string)null);
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Domain.Aggregates.StockLog", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<uint>("Id"));

                    b.Property<int>("ChangeQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("change_quantity");

                    b.Property<string>("_packageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_code");

                    b.HasKey("Id");

                    b.HasIndex("_packageCode");

                    b.ToTable("stock_logs", (string)null);
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Domain.Aggregates.StockLog", b =>
                {
                    b.HasOne("AZ.Integrator.Stocks.Domain.Aggregates.Stock", null)
                        .WithMany("StockLogs")
                        .HasForeignKey("_packageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AZ.Integrator.Stocks.Domain.Aggregates.ValueObjects.OperatorCreationInformation", "CreationInformation", b1 =>
                        {
                            b1.Property<uint>("StockLogId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("OperatorId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by");

                            b1.HasKey("StockLogId");

                            b1.ToTable("stock_logs");

                            b1.WithOwner()
                                .HasForeignKey("StockLogId");
                        });

                    b.Navigation("CreationInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Domain.Aggregates.Stock", b =>
                {
                    b.Navigation("StockLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
