// <auto-generated />
using System;
using AZ.Integrator.Stocks.Infrastructure.Persistence.EF.View;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AZ.Integrator.Stocks.Infrastructure.Persistence.EF.View.Migrations
{
    [DbContext(typeof(StockDataViewContext))]
    [Migration("20250716111717_InitStockGroupsView")]
    partial class InitStockGroupsView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AZ.Integrator.Stocks.Infrastructure.Persistence.EF.View.ViewModels.StockGroupViewModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable((string)null);

                    b.ToView("stock_groups_view", (string)null);
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Infrastructure.Persistence.EF.View.ViewModels.StockLogViewModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("ChangeQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("change_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_code");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PackageCode");

                    b.ToTable((string)null);

                    b.ToView("stock_logs_view", (string)null);
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Infrastructure.Persistence.EF.View.ViewModels.StockViewModel", b =>
                {
                    b.Property<string>("PackageCode")
                        .HasColumnType("text")
                        .HasColumnName("package_code");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("PackageCode");

                    b.HasIndex("GroupId");

                    b.ToTable((string)null);

                    b.ToView("stocks_view", (string)null);
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Infrastructure.Persistence.EF.View.ViewModels.StockLogViewModel", b =>
                {
                    b.HasOne("AZ.Integrator.Stocks.Infrastructure.Persistence.EF.View.ViewModels.StockViewModel", null)
                        .WithMany("Logs")
                        .HasForeignKey("PackageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Infrastructure.Persistence.EF.View.ViewModels.StockViewModel", b =>
                {
                    b.HasOne("AZ.Integrator.Stocks.Infrastructure.Persistence.EF.View.ViewModels.StockGroupViewModel", null)
                        .WithMany("Stocks")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Infrastructure.Persistence.EF.View.ViewModels.StockGroupViewModel", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("AZ.Integrator.Stocks.Infrastructure.Persistence.EF.View.ViewModels.StockViewModel", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
