// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace AZ.Integrator.Stocks.Infrastructure.Persistence.EF.View.Migrations
{
    [DbContext(typeof(StockDataViewContext))]
    partial class StockDataViewContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AZ.Integrator.Shared.Infrastructure.Persistence.EF.DbContexts.View.ViewModels.StockLogViewModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("ChangeQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("change_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("PackageCode")
                        .HasColumnType("text")
                        .HasColumnName("package_code");

                    b.HasKey("Id");

                    b.HasIndex("PackageCode");

                    b.ToTable((string)null);

                    b.ToView("stock_logs_view", (string)null);
                });

            modelBuilder.Entity("AZ.Integrator.Shared.Infrastructure.Persistence.EF.DbContexts.View.ViewModels.StockViewModel", b =>
                {
                    b.Property<string>("PackageCode")
                        .HasColumnType("text")
                        .HasColumnName("package_code");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("PackageCode");

                    b.ToTable((string)null);

                    b.ToView("stocks_view", (string)null);
                });

            modelBuilder.Entity("AZ.Integrator.Shared.Infrastructure.Persistence.EF.DbContexts.View.ViewModels.StockLogViewModel", b =>
                {
                    b.HasOne("AZ.Integrator.Shared.Infrastructure.Persistence.EF.DbContexts.View.ViewModels.StockViewModel", null)
                        .WithMany("Logs")
                        .HasForeignKey("PackageCode");
                });

            modelBuilder.Entity("AZ.Integrator.Shared.Infrastructure.Persistence.EF.DbContexts.View.ViewModels.StockViewModel", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
