services:
  api:
    image: az.integrator.api
    container_name: az-integrator-api
    build:
      context: .
      dockerfile: AZ.Integrator.Api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "6011:80"
      - "6010:443"
    networks:
      - az
    volumes:
      - ./https:/app/https
    healthcheck:
      test: curl --fail http://localhost/api/healthz || exit 1
      interval: 5s
      retries: 5
      timeout: 10s
      
  dbup:
    image: az.integrator.dbup
    container_name: az-integrator-dbup
    build:
      context: .
      dockerfile: AZ.Integrator.DbUp/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - az
    stop_signal: SIGINT
    tty: true
    stdin_open: true

  db:
    image: "postgres:15"
    container_name: az-integrator-db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - az
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    ports:
      - "9080:8443"
    container_name: az-integrator-keycloak
    command: start-dev --https-port=8443
    networks:
      - az
    volumes:
      - ./https/:/opt/keycloak/conf
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local

networks:
  az:
    driver: bridge
