version: '3.4'

services:
  api:
    environment:
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
      - Infrastructure__Postgres__ConnectionStringApplication=Server=db;Port=5432;Database=integrator;Username=postgres;Password=postgres;
    ports:
      - "80"

  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=integrator