version: '3.4'

services:
  api:
    environment:
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
      - Infrastructure__Postgres__ConnectionStringApplication=Server=db;Port=5432;Database=integrator;Username=postgres;Password=postgres;
      - Infrastructure__Postgres__ConnectionStringHangfire=Server=db;Port=5432;Database=integrator;Username=postgres;Password=postgres;
      - Infrastructure__Allegro__RedirectUri=http://host.docker.internal:6010/auth/allegro-auth-callback
      - Infrastructure__Keycloak__Authority=http://host.docker.internal:9080/realms/az-integrator
      - Infrastructure__Keycloak__AuthorizationUrl=http://host.docker.internal:9080/realms/az-integrator/protocol/openid-connect/auth
      - Infrastructure__Keycloak__TokenUrl=http://host.docker.internal:9080/realms/az-integrator/protocol/openid-connect/token
    ports:
      - "80"

  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=integrator
        
  keycloak:
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      
      KC_HOSTNAME: 192.168.0.185
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 9080:8080